[package]
name = "engine_ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "In-game UI system"

[dependencies]
glam = { workspace = true }
log = { workspace = true }
engine_render = { workspace = true }
